package com.example.progetto.AreeBiblioteca

import android.content.Intent
import android.os.Bundle
import android.widget.Button
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.lifecycle.lifecycleScope
import com.example.progetto.dataBase.DBViewModel
import com.example.progetto.Entity.Libro
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import com.example.progetto.R


class Biblioteca : AppCompatActivity() {

    private lateinit var dbViewModel: DBViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_biblioteca)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.gridLayoutBiblioteca)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        val bottoneLinguistica: Button = findViewById(R.id.linguistica)
        val bottoneMatematica: Button = findViewById(R.id.matematica)
        val bottoneInformatica: Button = findViewById(R.id.informatica)
        val bottoneGiuridico: Button = findViewById(R.id.giuridica)
        val bottoneEconomico: Button = findViewById(R.id.economica)
        val bottoneStorico: Button = findViewById(R.id.storica)
        val bottoneFilosofico: Button = findViewById(R.id.filosofica)
        val bottonePsicologico: Button = findViewById(R.id.psicologica)
        val bottonePedagogico: Button = findViewById(R.id.pedagogica)

        dbViewModel = DBViewModel(application)

        // Inizio inserimento libri
        inserisciLibri()

        val linguistica: String= "linguistica"

        bottoneLinguistica.setOnClickListener {
            val intent = Intent(this, Area_Linguistica::class.java).apply {
                intent.putExtra("area", linguistica)
            }
            startActivity(intent)
        }

        bottoneMatematica.setOnClickListener {
            val intent = Intent(this, Area_Matematica::class.java).apply {
                intent.putExtra("area", "Matematica")
            }
            startActivity(intent)
        }

        bottoneInformatica.setOnClickListener {
            val intent = Intent(this, Area_Informatica::class.java).apply {
                intent.putExtra("area", "Informatica")
            }
            startActivity(intent)
        }

        bottoneGiuridico.setOnClickListener {
            val intent = Intent(this, Area_Giuridica::class.java).apply {
                intent.putExtra("area", "Giuridico")
            }
            startActivity(intent)
        }

        bottoneEconomico.setOnClickListener {
            val intent = Intent(this, Area_Economica::class.java).apply {
                intent.putExtra("area", "Economica")
            }
            startActivity(intent)
        }

        bottoneStorico.setOnClickListener {
            val intent = Intent(this, Area_Storica::class.java).apply {
                intent.putExtra("area", "Storico")
            }
            startActivity(intent)
        }

        bottoneFilosofico.setOnClickListener {
            val intent = Intent(this, Area_Filosofica::class.java).apply {
                intent.putExtra("area", "Filosofico")
            }
            startActivity(intent)
        }

        bottonePsicologico.setOnClickListener {
            val intent = Intent(this, Area_Psicologica::class.java).apply {
                intent.putExtra("area", "Psicologico")
            }
            startActivity(intent)
        }

        bottonePedagogico.setOnClickListener {
            val intent = Intent(this, Area_Pedagogica::class.java).apply {
                intent.putExtra("area", "Pedagogico")
            }
            startActivity(intent)
        }
    }

    private fun inserisciLibri() {
        val libro1 = Libro(name = "Il Signore degli Anelli", autore = "J.R.R. Tolkien", settore = "Fantasy")
        val libro2 = Libro(name = "Orgoglio e Pregiudizio", autore = "Jane Austen", settore = "Romanzo")
        val libro3 = Libro(name = "Le Cronache del Ghiaccio e del Fuoco: Il Trono di Spade", autore = "George R.R. Martin", settore = "Fantasy")
        val libro4 = Libro(name = "1984", autore = "George Orwell", settore = "linguistica")
        val libro5 = Libro(name = "Il Piccolo Principe", autore = "Antoine de Saint-Exupéry", settore = "linguistica")
        val libro6 = Libro(name = "Delitto e Castigo", autore = "Fëdor Dostoevskij", settore = "Classico")
        val libro7 = Libro(name = "Cime tempestose", autore = "Emily Brontë", settore = "Gotico")
        val libro8 = Libro(name = "L'Odissea", autore = "Omero", settore = "linguistica")
        val libro9 = Libro(name = "Moby Dick", autore = "Herman Melville", settore = "Avventura")
        val libro10 = Libro(name = "Il Processo", autore = "Franz Kafka", settore = "linguistica")
        val libro11 = Libro(name = "Dieci piccoli indiani", autore = "Agatha Christie", settore = "linguistica")
        val libro12 = Libro(name = "Il Nome della Rosa", autore = "Umberto Eco", settore = "Storico")
        val libro13 = Libro(name = "Neuromante", autore = "William Gibson", settore = "linguistica")
        val libro14 = Libro(name = "Fondazione", autore = "Isaac Asimov", settore = "Fantascienza")
        val libro15 = Libro(name = "Dune", autore = "Frank Herbert", settore = "linguistica")
        val libro16 = Libro(name = "La struttura delle lingue", autore = "Noam Chomsky", settore = "linguistica")
        val libro17 = Libro(name = "Introduzione alla linguistica generale", autore = "Ferdinand de Saussure", settore = "linguistica")
        val libro18 = Libro(name = "Linguistica generale", autore = "Morris Halle", settore = "linguistica")
        val libro19 = Libro(name = "Language and Mind", autore = "Noam Chomsky", settore = "linguistica")
        val libro20 = Libro(name = "Semantica e Pragmatica", autore = "Paul Grice", settore = "linguistica")
        val libro21 = Libro(name = "La lingua come sistema di segni", autore = "Ferdinand de Saussure", settore = "linguistica")
        val libro22 = Libro(name = "Lingua e cultura", autore = "Edward Sapir", settore = "linguistica")
        val libro23 = Libro(name = "I segni del linguaggio", autore = "Charles Peirce", settore = "linguistica")
        val libro24 = Libro(name = "Sintassi delle lingue del mondo", autore = "Joseph Greenberg", settore = "linguistica")
        val libro25 = Libro(name = "Linguistica cognitiva", autore = "George Lakoff", settore = "linguistica")
        val libro26 = Libro(name = "Fonologia e fonetica", autore = "Peter Ladefoged", settore = "linguistica")
        val libro27 = Libro(name = "Lingue e linguaggi", autore = "Roman Jakobson", settore = "linguistica")
        val libro28 = Libro(name = "Evoluzione del linguaggio", autore = "Derek Bickerton", settore = "linguistica")
        val libro29 = Libro(name = "Linguistica comparata", autore = "Franz Bopp", settore = "linguistica")
        val libro30 = Libro(name = "La grammatica universale", autore = "Noam Chomsky", settore = "linguistica")
        val libro31 = Libro(name = "Teoria della comunicazione", autore = "Roman Jakobson", settore = "linguistica")
        val libro32 = Libro(name = "Il significato nelle lingue", autore = "Paul Grice", settore = "linguistica")
        val libro33 = Libro(name = "Linguistica storica", autore = "August Schleicher", settore = "linguistica")
        val libro34 = Libro(name = "Sociolinguistica", autore = "William Labov", settore = "linguistica")
        val libro35 = Libro(name = "Psicolinguistica", autore = "Jean Berko Gleason", settore = "linguistica")
        val libro36 = Libro(name = "Linguaggio e società", autore = "Dell Hymes", settore = "linguistica")
        val libro37 = Libro(name = "Il potere del linguaggio", autore = "Deborah Tannen", settore = "linguistica")
        val libro38 = Libro(name = "Traduzione e linguistica", autore = "Eugene Nida", settore = "linguistica")
        val libro39 = Libro(name = "Grammatica del discorso", autore = "Michael Halliday", settore = "linguistica")
        val libro40 = Libro(name = "Lingue in contatto", autore = "Uriel Weinreich", settore = "linguistica")
        val libro41 = Libro(name = "Semiotica e linguistica", autore = "Umberto Eco", settore = "linguistica")
        val libro42 = Libro(name = "Analisi del testo linguistico", autore = "Teun van Dijk", settore = "linguistica")
        val libro43 = Libro(name = "Lingue artificiali", autore = "John Quijada", settore = "linguistica")
        val libro44 = Libro(name = "Pragmatica linguistica", autore = "Stephen Levinson", settore = "linguistica")
        val libro45 = Libro(name = "Linguaggio e cognizione", autore = "Ray Jackendoff", settore = "linguistica")

        val libro46 = Libro(name = "Clean Code", autore = "Robert C. Martin", settore = "Informatica")
        val libro47 = Libro(name = "Introduction to Algorithms", autore = "Thomas H. Cormen", settore = "Informatica")
        val libro48 = Libro(name = "The Pragmatic Programmer", autore = "Andrew Hunt", settore = "Informatica")
        val libro49 = Libro(name = "Design Patterns", autore = "Erich Gamma", settore = "Informatica")
        val libro50 = Libro(name = "Artificial Intelligence: A Modern Approach", autore = "Stuart Russell", settore = "Informatica")
        val libro51 = Libro(name = "Computer Networking: A Top-Down Approach", autore = "James Kurose", settore = "Informatica")
        val libro52 = Libro(name = "The Mythical Man-Month", autore = "Frederick P. Brooks Jr.", settore = "Informatica")
        val libro53 = Libro(name = "Structure and Interpretation of Computer Programs", autore = "Harold Abelson", settore = "Informatica")
        val libro54 = Libro(name = "The Art of Computer Programming", autore = "Donald E. Knuth", settore = "Informatica")
        val libro55 = Libro(name = "Python Crash Course", autore = "Eric Matthes", settore = "Informatica")
        val libro56 = Libro(name = "Algorithms", autore = "Robert Sedgewick", settore = "Informatica")
        val libro57 = Libro(name = "Operating System Concepts", autore = "Abraham Silberschatz", settore = "Informatica")
        val libro58 = Libro(name = "Code Complete", autore = "Steve McConnell", settore = "Informatica")
        val libro59 = Libro(name = "Software Engineering", autore = "Ian Sommerville", settore = "Informatica")
        val libro60 = Libro(name = "Computer Architecture: A Quantitative Approach", autore = "John L. Hennessy", settore = "Informatica")
        val libro61 = Libro(name = "Artificial Intelligence: Foundations of Computational Agents", autore = "David L. Poole", settore = "Informatica")
        val libro62 = Libro(name = "Compilers: Principles, Techniques, and Tools", autore = "Alfred V. Aho", settore = "Informatica")
        val libro63 = Libro(name = "Java: The Complete Reference", autore = "Herbert Schildt", settore = "Informatica")
        val libro64 = Libro(name = "Design Patterns: Elements of Reusable Object-Oriented Software", autore = "Erich Gamma", settore = "Informatica")
        val libro65 = Libro(name = "Distributed Systems: Concepts and Design", autore = "George Coulouris", settore = "Informatica")
        val libro66 = Libro(name = "Introduction to the Theory of Computation", autore = "Michael Sipser", settore = "Informatica")
        val libro67 = Libro(name = "Modern Operating Systems", autore = "Andrew S. Tanenbaum", settore = "Informatica")
        val libro68 = Libro(name = "Linux Pocket Guide", autore = "Daniel J. Barrett", settore = "Informatica")
        val libro69 = Libro(name = "Eloquent JavaScript", autore = "Marijn Haverbeke", settore = "Informatica")
        val libro70 = Libro(name = "The C Programming Language", autore = "Brian W. Kernighan", settore = "Informatica")

        val libro71 = Libro(name = "Principles of Economics", autore = "N. Gregory Mankiw", settore = "Economica")
        val libro72 = Libro(name = "The Wealth of Nations", autore = "Adam Smith", settore = "Economica")
        val libro73 = Libro(name = "Capital in the Twenty-First Century", autore = "Thomas Piketty", settore = "Economica")
        val libro74 = Libro(name = "Freakonomics", autore = "Steven D. Levitt", settore = "Economica")
        val libro75 = Libro(name = "The Big Short", autore = "Michael Lewis", settore = "Economica")
        val libro76 = Libro(name = "The General Theory of Employment, Interest, and Money", autore = "John Maynard Keynes", settore = "Economica")
        val libro77 = Libro(name = "Thinking, Fast and Slow", autore = "Daniel Kahneman", settore = "Economica")
        val libro78 = Libro(name = "The Road to Serfdom", autore = "Friedrich Hayek", settore = "Economica")
        val libro79 = Libro(name = "Das Kapital", autore = "Karl Marx", settore = "Economica")
        val libro80 = Libro(name = "The Intelligent Investor", autore = "Benjamin Graham", settore = "Economica")
        val libro81 = Libro(name = "The Origins of Political Order", autore = "Francis Fukuyama", settore = "Economica")
        val libro82 = Libro(name = "A Random Walk Down Wall Street", autore = "Burton G. Malkiel", settore = "Economica")
        val libro83 = Libro(name = "Good to Great", autore = "Jim Collins", settore = "Economica")
        val libro84 = Libro(name = "The Lean Startup", autore = "Eric Ries", settore = "Economica")
        val libro85 = Libro(name = "The Black Swan", autore = "Nassim Nicholas Taleb", settore = "Economica")
        val libro86 = Libro(name = "The End of Poverty", autore = "Jeffrey Sachs", settore = "Economica")
        val libro87 = Libro(name = "Globalization and Its Discontents", autore = "Joseph E. Stiglitz", settore = "Economica")
        val libro88 = Libro(name = "The New Jim Crow", autore = "Michelle Alexander", settore = "Economica")
        val libro89 = Libro(name = "Debt: The First 5000 Years", autore = "David Graeber", settore = "Economica")
        val libro90 = Libro(name = "The Shock Doctrine", autore = "Naomi Klein", settore = "Economica")
        val libro91 = Libro(name = "The Power of Habit", autore = "Charles Duhigg", settore = "Economica")
        val libro92 = Libro(name = "Rich Dad Poor Dad", autore = "Robert T. Kiyosaki", settore = "Economica")
        val libro93 = Libro(name = "Economics in One Lesson", autore = "Henry Hazlitt", settore = "Economica")
        val libro94 = Libro(name = "The Ascent of Money", autore = "Niall Ferguson", settore = "Economica")
        val libro95 = Libro(name = "The Four", autore = "Scott Galloway", settore = "Economica")
        val libro96 = Libro(name = "The Millionaire Next Door", autore = "Thomas J. Stanley", settore = "Economica")

        val libro101 = Libro(name = "The Elements", autore = "Euclid", settore = "Matematica")
        val libro102 = Libro(name = "Principia Mathematica", autore = "Alfred North Whitehead, Bertrand Russell", settore = "Matematica")
        val libro103 = Libro(name = "The Princeton Companion to Mathematics", autore = "Timothy Gowers", settore = "Matematica")
        val libro104 = Libro(name = "Gödel, Escher, Bach: An Eternal Golden Braid", autore = "Douglas Hofstadter", settore = "Matematica")
        val libro105 = Libro(name = "Mathematics: Its Content, Methods, and Meaning", autore = "A.D. Aleksandrov", settore = "Matematica")
        val libro106 = Libro(name = "Introduction to Probability", autore = "Dimitri P. Bertsekas, John N. Tsitsiklis", settore = "Matematica")
        val libro107 = Libro(name = "Calculus", autore = "Michael Spivak", settore = "Matematica")
        val libro108 = Libro(name = "A Brief History of Time", autore = "Stephen Hawking", settore = "Matematica")
        val libro109 = Libro(name = "The Art of Computer Programming", autore = "Donald E. Knuth", settore = "Matematica")
        val libro110 = Libro(name = "Flatland: A Romance of Many Dimensions", autore = "Edwin A. Abbott", settore = "Matematica")
        val libro111 = Libro(name = "The Feynman Lectures on Physics", autore = "Richard P. Feynman", settore = "Matematica")
        val libro112 = Libro(name = "The Mathematical Theory of Communication", autore = "Claude E. Shannon, Warren Weaver", settore = "Matematica")
        val libro113 = Libro(name = "How to Prove It: A Structured Approach", autore = "Daniel Velleman", settore = "Matematica")
        val libro114 = Libro(name = "The Joy of x: A Guided Tour of Math, from One to Infinity", autore = "Steven Strogatz", settore = "Matematica")
        val libro115 = Libro(name = "The Code Book: The Science of Secrecy from Ancient Egypt to Quantum Cryptography", autore = "Simon Singh", settore = "Matematica")
        val libro116 = Libro(name = "An Introduction to Mathematical Thinking", autore = "William P. Thurston", settore = "Matematica")
        val libro117 = Libro(name = "Mathematics for the Nonmathematician", autore = "Morris Kline", settore = "Matematica")
        val libro118 = Libro(name = "The Metric Tensor", autore = "Michael P. Do Carmo", settore = "Matematica")
        val libro119 = Libro(name = "Differential Geometry of Curves and Surfaces", autore = "Manfredo P. do Carmo", settore = "Matematica")
        val libro120 = Libro(name = "Linear Algebra Done Right", autore = "Sheldon Axler", settore = "Matematica")
        val libro121 = Libro(name = "Concrete Mathematics", autore = "Ronald L. Graham, Donald E. Knuth, Oren Patashnik", settore = "Matematica")
        val libro122 = Libro(name = "Introduction to Graph Theory", autore = "Douglas B. West", settore = "Matematica")
        val libro123 = Libro(name = "Calculus of Variations", autore = "I.M. Gelfand, S.V. Fomin", settore = "Matematica")
        val libro124 = Libro(name = "Number Theory", autore = "David M. Burton", settore = "Matematica")
        val libro125 = Libro(name = "Topology", autore = "James R. Munkres", settore = "Matematica")

        val libro126 = Libro(name = "Il Contratto", autore = "René David", settore = "Giuridico")
        val libro127 = Libro(name = "Lezioni di diritto privato", autore = "Giovanni Costa", settore = "Giuridico")
        val libro128 = Libro(name = "I principi del diritto civile", autore = "Francesco Galgano", settore = "Giuridico")
        val libro129 = Libro(name = "Manuale di diritto costituzionale", autore = "Giuseppe Branca", settore = "Giuridico")
        val libro130 = Libro(name = "Diritto penale", autore = "Francesco Salvia", settore = "Giuridico")
        val libro131 = Libro(name = "Teoria generale del diritto", autore = "Enrico Colombo", settore = "Giuridico")
        val libro132 = Libro(name = "Diritto internazionale", autore = "Antonio Cassese", settore = "Giuridico")
        val libro133 = Libro(name = "Introduzione al diritto comparato", autore = "Pierluigi Chiassoni", settore = "Giuridico")
        val libro134 = Libro(name = "Trattato di diritto civile", autore = "Vittorio Sgroi", settore = "Giuridico")
        val libro135 = Libro(name = "Il diritto romano", autore = "Giuseppe Chiovenda", settore = "Giuridico")
        val libro136 = Libro(name = "Manuale di diritto commerciale", autore = "Giuseppe Benacchio", settore = "Giuridico")
        val libro137 = Libro(name = "Diritto amministrativo", autore = "Sabino Cassese", settore = "Giuridico")
        val libro138 = Libro(name = "Diritto di famiglia", autore = "Alberto L. A. Zamboni", settore = "Giuridico")
        val libro139 = Libro(name = "Codice civile commentato", autore = "Giorgio Giampaoletti", settore = "Giuridico")
        val libro140 = Libro(name = "Il diritto del lavoro", autore = "Giorgio Ghezzi", settore = "Giuridico")
        val libro141 = Libro(name = "Diritto penale: Parte generale", autore = "Vincenzo Spataro", settore = "Giuridico")
        val libro142 = Libro(name = "Manuale di diritto tributario", autore = "Giuseppe Zizzo", settore = "Giuridico")
        val libro143 = Libro(name = "I diritti fondamentali", autore = "Luigi Ferrajoli", settore = "Giuridico")
        val libro144 = Libro(name = "La costituzione italiana", autore = "Massimo Luciani", settore = "Giuridico")
        val libro145 = Libro(name = "Diritto commerciale internazionale", autore = "Federico M. Mucci", settore = "Giuridico")
        val libro146 = Libro(name = "Lezioni di diritto pubblico", autore = "Vittorio Emanuele Orlando", settore = "Giuridico")
        val libro147 = Libro(name = "Il diritto della concorrenza", autore = "Francesco Sticchi Damiani", settore = "Giuridico")
        val libro148 = Libro(name = "Storia del diritto medievale", autore = "Giorgio Vasari", settore = "Giuridico")
        val libro149 = Libro(name = "La giustizia penale", autore = "Giuliano Marini", settore = "Giuridico")
        val libro150 = Libro(name = "I principi del diritto europeo", autore = "Rainer Arnold", settore = "Giuridico")

        val libro151 = Libro(name = "Storia della Roma antica", autore = "Theodor Mommsen", settore = "Storico")
        val libro152 = Libro(name = "Le origini della seconda guerra mondiale", autore = "A.J.P. Taylor", settore = "Storico")
        val libro153 = Libro(name = "Il Medioevo", autore = "Jacques Le Goff", settore = "Storico")
        val libro154 = Libro(name = "Storia moderna", autore = "Peter N. Stearns", settore = "Storico")
        val libro155 = Libro(name = "La storia della Grecia antica", autore = "Robin Osborne", settore = "Storico")
        val libro156 = Libro(name = "Le guerre puniche", autore = "Adrian Goldsworthy", settore = "Storico")
        val libro157 = Libro(name = "Storia dell'Europa moderna", autore = "Norman Davies", settore = "Storico")
        val libro158 = Libro(name = "La rivoluzione francese", autore = "Georges Lefebvre", settore = "Storico")
        val libro159 = Libro(name = "Storia della Cina", autore = "John King Fairbank", settore = "Storico")
        val libro160 = Libro(name = "La storia delle Crociate", autore = "Steven Runciman", settore = "Storico")
        val libro161 = Libro(name = "La storia dell'Antica Roma", autore = "Mary Beard", settore = "Storico")
        val libro162 = Libro(name = "Il risorgimento italiano", autore = "Alessandro Barbero", settore = "Storico")
        val libro163 = Libro(name = "Storia della Seconda Guerra Mondiale", autore = "Winston Churchill", settore = "Storico")
        val libro164 = Libro(name = "La guerra dei trent'anni", autore = "C.V. Wedgwood", settore = "Storico")
        val libro165 = Libro(name = "Storia della filosofia medievale", autore = "Etienne Gilson", settore = "Storico")
        val libro166 = Libro(name = "La guerra civile americana", autore = "James McPherson", settore = "Storico")
        val libro167 = Libro(name = "La storia delle civiltà", autore = "Will Durant", settore = "Storico")
        val libro168 = Libro(name = "Il mondo antico", autore = "M.I. Finley", settore = "Storico")
        val libro169 = Libro(name = "Le origini del fascismo", autore = "Renzo De Felice", settore = "Storico")
        val libro170 = Libro(name = "La storia della Russia", autore = "Robert Service", settore = "Storico")
        val libro171 = Libro(name = "Storia del nazismo", autore = "Ian Kershaw", settore = "Storico")
        val libro172 = Libro(name = "La storia della Grecia", autore = "N.G.L. Hammond", settore = "Storico")
        val libro173 = Libro(name = "Il Novecento", autore = "Eric Hobsbawm", settore = "Storico")
        val libro174 = Libro(name = "La Storia del Cristianesimo", autore = "Jaroslav Pelikan", settore = "Storico")
        val libro175 = Libro(name = "Il Medioevo e la nascita dell'Europa", autore = "Barbara Tuchman", settore = "Storico")

        val libro176 = Libro(name = "La Repubblica", autore = "Platone", settore = "Filosofico")
        val libro177 = Libro(name = "Critica della ragion pura", autore = "Immanuel Kant", settore = "Filosofico")
        val libro178 = Libro(name = "Così parlò Zarathustra", autore = "Friedrich Nietzsche", settore = "Filosofico")
        val libro179 = Libro(name = "Il mondo come volontà e rappresentazione", autore = "Arthur Schopenhauer", settore = "Filosofico")
        val libro180 = Libro(name = "Fenomenologia dello spirito", autore = "Georg Wilhelm Friedrich Hegel", settore = "Filosofico")
        val libro181 = Libro(name = "Meditazioni", autore = "Marco Aurelio", settore = "Filosofico")
        val libro182 = Libro(name = "La genealogia della morale", autore = "Friedrich Nietzsche", settore = "Filosofico")
        val libro183 = Libro(name = "La logica", autore = "Aristotele", settore = "Filosofico")
        val libro184 = Libro(name = "Essere e tempo", autore = "Martin Heidegger", settore = "Filosofico")
        val libro185 = Libro(name = "Il contratto sociale", autore = "Jean-Jacques Rousseau", settore = "Filosofico")
        val libro186 = Libro(name = "Critica della ragion pratica", autore = "Immanuel Kant", settore = "Filosofico")
        val libro187 = Libro(name = "Il discorso sul metodo", autore = "René Descartes", settore = "Filosofico")
        val libro188 = Libro(name = "La struttura delle rivoluzioni scientifiche", autore = "Thomas S. Kuhn", settore = "Filosofico")
        val libro189 = Libro(name = "Il capitale", autore = "Karl Marx", settore = "Filosofico")
        val libro190 = Libro(name = "La società industriale e il suo futuro", autore = "Herbert Marcuse", settore = "Filosofico")
        val libro191 = Libro(name = "Il problema dell'induzione", autore = "David Hume", settore = "Filosofico")
        val libro192 = Libro(name = "Trattato di filosofia", autore = "Baruch Spinoza", settore = "Filosofico")
        val libro193 = Libro(name = "La morale della libertà", autore = "Jean-Paul Sartre", settore = "Filosofico")
        val libro194 = Libro(name = "Filosofia della scienza", autore = "Karl Popper", settore = "Filosofico")
        val libro195 = Libro(name = "La dialettica dell'illuminismo", autore = "Theodor W. Adorno", settore = "Filosofico")
        val libro196 = Libro(name = "Filosofia della storia", autore = "Georg Wilhelm Friedrich Hegel", settore = "Filosofico")
        val libro197 = Libro(name = "Il pensiero occidentale", autore = "Giovanni Reale", settore = "Filosofico")
        val libro198 = Libro(name = "La filosofia della libertà", autore = "Rudolf Steiner", settore = "Filosofico")
        val libro199 = Libro(name = "Logica e linguaggio", autore = "Ludwig Wittgenstein", settore = "Filosofico")
        val libro200 = Libro(name = "Introduzione alla filosofia", autore = "Niccolò Machiavelli", settore = "Filosofico")

        val libro201 = Libro(name = "L'interpretazione dei sogni", autore = "Sigmund Freud", settore = "Psicologico")
        val libro202 = Libro(name = "Psicologia delle masse", autore = "Sigmund Freud", settore = "Psicologico")
        val libro203 = Libro(name = "Il disagio della civiltà", autore = "Sigmund Freud", settore = "Psicologico")
        val libro204 = Libro(name = "Introduzione alla psicoanalisi", autore = "Sigmund Freud", settore = "Psicologico")
        val libro205 = Libro(name = "Psicologia e educazione", autore = "John Dewey", settore = "Psicologico")
        val libro206 = Libro(name = "Il comportamento dei gruppi", autore = "William McDougall", settore = "Psicologico")
        val libro207 = Libro(name = "La psicologia del bambino", autore = "Jean Piaget", settore = "Psicologico")
        val libro208 = Libro(name = "Psicologia sociale", autore = "Gordon Allport", settore = "Psicologico")
        val libro209 = Libro(name = "Psicologia della personalità", autore = "Erik Erikson", settore = "Psicologico")
        val libro210 = Libro(name = "Psicologia dinamica", autore = "Carl Jung", settore = "Psicologico")
        val libro211 = Libro(name = "Il comportamento umano", autore = "B.F. Skinner", settore = "Psicologico")
        val libro212 = Libro(name = "Teoria dell'apprendimento", autore = "Edward Thorndike", settore = "Psicologico")
        val libro213 = Libro(name = "Psicologia cognitiva", autore = "Ulric Neisser", settore = "Psicologico")
        val libro214 = Libro(name = "Sviluppo e psicologia del bambino", autore = "Lev Vygotsky", settore = "Psicologico")
        val libro215 = Libro(name = "La mente sociale", autore = "William McDougall", settore = "Psicologico")
        val libro216 = Libro(name = "Psicologia delle emozioni", autore = "Paul Ekman", settore = "Psicologico")
        val libro217 = Libro(name = "Psicologia del lavoro", autore = "Hugo Münsterberg", settore = "Psicologico")
        val libro218 = Libro(name = "Il pensiero positivo", autore = "Norman Vincent Peale", settore = "Psicologico")
        val libro219 = Libro(name = "Psicoterapia", autore = "Carl Rogers", settore = "Psicologico")
        val libro220 = Libro(name = "Psicologia dell'adolescenza", autore = "David Elkind", settore = "Psicologico")
        val libro221 = Libro(name = "La psiche e il corpo", autore = "Sigmund Freud", settore = "Psicologico")
        val libro222 = Libro(name = "Teoria della motivazione", autore = "Abraham Maslow", settore = "Psicologico")
        val libro223 = Libro(name = "Psicologia dell'apprendimento", autore = "B.F. Skinner", settore = "Psicologico")
        val libro224 = Libro(name = "Psicologia della salute", autore = "Robert Sapolsky", settore = "Psicologico")
        val libro225 = Libro(name = "Psicologia della comunicazione", autore = "Wilbur Schramm", settore = "Psicologico")

        val libro226 = Libro(name = "Pedagogia", autore = "Giovanni Gentile", settore = "Pedagogico")
        val libro227 = Libro(name = "La scuola come comunità", autore = "John Dewey", settore = "Pedagogico")
        val libro228 = Libro(name = "L'educazione come libertà", autore = "Paulo Freire", settore = "Pedagogico")
        val libro229 = Libro(name = "La pedagogia del futuro", autore = "Maria Montessori", settore = "Pedagogico")
        val libro230 = Libro(name = "La pedagogia scientifica", autore = "Gianfranco Zavalloni", settore = "Pedagogico")
        val libro231 = Libro(name = "L'arte dell'insegnamento", autore = "Richard Sennett", settore = "Pedagogico")
        val libro232 = Libro(name = "Il diritto all'educazione", autore = "Nel Noddings", settore = "Pedagogico")
        val libro233 = Libro(name = "L'educazione dell'infanzia", autore = "Jean Piaget", settore = "Pedagogico")
        val libro234 = Libro(name = "Teoria pedagogica", autore = "Erik Erikson", settore = "Pedagogico")
        val libro235 = Libro(name = "La scuola come agenzia sociale", autore = "Durkheim Emile", settore = "Pedagogico")
        val libro236 = Libro(name = "Educare alla vita", autore = "Giorgio Santi", settore = "Pedagogico")
        val libro237 = Libro(name = "La formazione degli insegnanti", autore = "Robert L. Ebel", settore = "Pedagogico")
        val libro238 = Libro(name = "La psicologia dell'insegnamento", autore = "Lev Vygotsky", settore = "Pedagogico")
        val libro239 = Libro(name = "Metodi educativi", autore = "Gianfranco Zavalloni", settore = "Pedagogico")
        val libro240 = Libro(name = "Pedagogia della libertà", autore = "Paulo Freire", settore = "Pedagogico")
        val libro241 = Libro(name = "Pedagogia e cultura", autore = "John Dewey", settore = "Pedagogico")
        val libro242 = Libro(name = "L'educazione integrale", autore = "Maria Montessori", settore = "Pedagogico")
        val libro243 = Libro(name = "Educazione e crescita", autore = "Jean-Jacques Rousseau", settore = "Pedagogico")
        val libro244 = Libro(name = "Il futuro dell'educazione", autore = "Paulo Freire", settore = "Pedagogico")
        val libro245 = Libro(name = "Psicopedagogia", autore = "Sabrina D'Angelo", settore = "Pedagogico")
        val libro246 = Libro(name = "Educazione e inclusività", autore = "Sally Brown", settore = "Pedagogico")
        val libro247 = Libro(name = "Sociologia dell'educazione", autore = "Pierre Bourdieu", settore = "Pedagogico")
        val libro248 = Libro(name = "La pedagogia del bambino", autore = "Maria Montessori", settore = "Pedagogico")
        val libro249 = Libro(name = "L'insegnamento come arte", autore = "Maxine Greene", settore = "Pedagogico")
        val libro250 = Libro(name = "La didattica delle lingue", autore = "David Nunan", settore = "Pedagogico")

        lifecycleScope.launch {
            withContext(Dispatchers.IO) {
                dbViewModel.aggiungiLibro(libro1)
                dbViewModel.aggiungiLibro(libro2)
                dbViewModel.aggiungiLibro(libro3)
                dbViewModel.aggiungiLibro(libro4)
                dbViewModel.aggiungiLibro(libro5)
                dbViewModel.aggiungiLibro(libro6)
                dbViewModel.aggiungiLibro(libro7)
                dbViewModel.aggiungiLibro(libro8)
                dbViewModel.aggiungiLibro(libro9)
                dbViewModel.aggiungiLibro(libro10)
                dbViewModel.aggiungiLibro(libro11)
                dbViewModel.aggiungiLibro(libro12)
                dbViewModel.aggiungiLibro(libro13)
                dbViewModel.aggiungiLibro(libro14)
                dbViewModel.aggiungiLibro(libro15)
                dbViewModel.aggiungiLibro(libro1)
                dbViewModel.aggiungiLibro(libro2)
                dbViewModel.aggiungiLibro(libro3)
                dbViewModel.aggiungiLibro(libro4)
                dbViewModel.aggiungiLibro(libro5)
                dbViewModel.aggiungiLibro(libro6)
                dbViewModel.aggiungiLibro(libro7)
                dbViewModel.aggiungiLibro(libro8)
                dbViewModel.aggiungiLibro(libro9)
                dbViewModel.aggiungiLibro(libro10)
                dbViewModel.aggiungiLibro(libro11)
                dbViewModel.aggiungiLibro(libro12)
                dbViewModel.aggiungiLibro(libro13)
                dbViewModel.aggiungiLibro(libro14)
                dbViewModel.aggiungiLibro(libro15)
                dbViewModel.aggiungiLibro(libro16)
                dbViewModel.aggiungiLibro(libro17)
                dbViewModel.aggiungiLibro(libro18)
                dbViewModel.aggiungiLibro(libro19)
                dbViewModel.aggiungiLibro(libro20)
                dbViewModel.aggiungiLibro(libro21)
                dbViewModel.aggiungiLibro(libro22)
                dbViewModel.aggiungiLibro(libro23)
                dbViewModel.aggiungiLibro(libro24)
                dbViewModel.aggiungiLibro(libro25)
                dbViewModel.aggiungiLibro(libro26)
                dbViewModel.aggiungiLibro(libro27)
                dbViewModel.aggiungiLibro(libro28)
                dbViewModel.aggiungiLibro(libro29)
                dbViewModel.aggiungiLibro(libro30)
                dbViewModel.aggiungiLibro(libro31)
                dbViewModel.aggiungiLibro(libro32)
                dbViewModel.aggiungiLibro(libro33)
                dbViewModel.aggiungiLibro(libro34)
                dbViewModel.aggiungiLibro(libro35)
                dbViewModel.aggiungiLibro(libro36)
                dbViewModel.aggiungiLibro(libro37)
                dbViewModel.aggiungiLibro(libro38)
                dbViewModel.aggiungiLibro(libro39)
                dbViewModel.aggiungiLibro(libro40)
                dbViewModel.aggiungiLibro(libro41)
                dbViewModel.aggiungiLibro(libro42)
                dbViewModel.aggiungiLibro(libro43)
                dbViewModel.aggiungiLibro(libro44)
                dbViewModel.aggiungiLibro(libro45)

                dbViewModel.aggiungiLibro(libro46)
                dbViewModel.aggiungiLibro(libro47)
                dbViewModel.aggiungiLibro(libro48)
                dbViewModel.aggiungiLibro(libro49)
                dbViewModel.aggiungiLibro(libro50)
                dbViewModel.aggiungiLibro(libro51)
                dbViewModel.aggiungiLibro(libro52)
                dbViewModel.aggiungiLibro(libro53)
                dbViewModel.aggiungiLibro(libro54)
                dbViewModel.aggiungiLibro(libro55)
                dbViewModel.aggiungiLibro(libro56)
                dbViewModel.aggiungiLibro(libro57)
                dbViewModel.aggiungiLibro(libro58)
                dbViewModel.aggiungiLibro(libro59)
                dbViewModel.aggiungiLibro(libro60)
                dbViewModel.aggiungiLibro(libro61)
                dbViewModel.aggiungiLibro(libro62)
                dbViewModel.aggiungiLibro(libro63)
                dbViewModel.aggiungiLibro(libro64)
                dbViewModel.aggiungiLibro(libro65)
                dbViewModel.aggiungiLibro(libro66)
                dbViewModel.aggiungiLibro(libro67)
                dbViewModel.aggiungiLibro(libro68)
                dbViewModel.aggiungiLibro(libro69)
                dbViewModel.aggiungiLibro(libro70)

                dbViewModel.aggiungiLibro(libro71)
                dbViewModel.aggiungiLibro(libro72)
                dbViewModel.aggiungiLibro(libro73)
                dbViewModel.aggiungiLibro(libro74)
                dbViewModel.aggiungiLibro(libro75)
                dbViewModel.aggiungiLibro(libro76)
                dbViewModel.aggiungiLibro(libro77)
                dbViewModel.aggiungiLibro(libro78)
                dbViewModel.aggiungiLibro(libro79)
                dbViewModel.aggiungiLibro(libro80)
                dbViewModel.aggiungiLibro(libro81)
                dbViewModel.aggiungiLibro(libro82)
                dbViewModel.aggiungiLibro(libro83)
                dbViewModel.aggiungiLibro(libro84)
                dbViewModel.aggiungiLibro(libro85)
                dbViewModel.aggiungiLibro(libro86)
                dbViewModel.aggiungiLibro(libro87)
                dbViewModel.aggiungiLibro(libro88)
                dbViewModel.aggiungiLibro(libro89)
                dbViewModel.aggiungiLibro(libro90)
                dbViewModel.aggiungiLibro(libro91)
                dbViewModel.aggiungiLibro(libro92)
                dbViewModel.aggiungiLibro(libro93)
                dbViewModel.aggiungiLibro(libro94)
                dbViewModel.aggiungiLibro(libro95)
                dbViewModel.aggiungiLibro(libro96)

                dbViewModel.aggiungiLibro(libro101)
                dbViewModel.aggiungiLibro(libro102)
                dbViewModel.aggiungiLibro(libro103)
                dbViewModel.aggiungiLibro(libro104)
                dbViewModel.aggiungiLibro(libro105)
                dbViewModel.aggiungiLibro(libro106)
                dbViewModel.aggiungiLibro(libro107)
                dbViewModel.aggiungiLibro(libro108)
                dbViewModel.aggiungiLibro(libro109)
                dbViewModel.aggiungiLibro(libro110)
                dbViewModel.aggiungiLibro(libro111)
                dbViewModel.aggiungiLibro(libro112)
                dbViewModel.aggiungiLibro(libro113)
                dbViewModel.aggiungiLibro(libro114)
                dbViewModel.aggiungiLibro(libro115)
                dbViewModel.aggiungiLibro(libro116)
                dbViewModel.aggiungiLibro(libro117)
                dbViewModel.aggiungiLibro(libro118)
                dbViewModel.aggiungiLibro(libro119)
                dbViewModel.aggiungiLibro(libro120)
                dbViewModel.aggiungiLibro(libro121)
                dbViewModel.aggiungiLibro(libro122)
                dbViewModel.aggiungiLibro(libro123)
                dbViewModel.aggiungiLibro(libro124)
                dbViewModel.aggiungiLibro(libro125)

                dbViewModel.aggiungiLibro(libro126)
                dbViewModel.aggiungiLibro(libro127)
                dbViewModel.aggiungiLibro(libro128)
                dbViewModel.aggiungiLibro(libro129)
                dbViewModel.aggiungiLibro(libro130)
                dbViewModel.aggiungiLibro(libro131)
                dbViewModel.aggiungiLibro(libro132)
                dbViewModel.aggiungiLibro(libro133)
                dbViewModel.aggiungiLibro(libro134)
                dbViewModel.aggiungiLibro(libro135)
                dbViewModel.aggiungiLibro(libro136)
                dbViewModel.aggiungiLibro(libro137)
                dbViewModel.aggiungiLibro(libro138)
                dbViewModel.aggiungiLibro(libro139)
                dbViewModel.aggiungiLibro(libro140)
                dbViewModel.aggiungiLibro(libro141)
                dbViewModel.aggiungiLibro(libro142)
                dbViewModel.aggiungiLibro(libro143)
                dbViewModel.aggiungiLibro(libro144)
                dbViewModel.aggiungiLibro(libro145)
                dbViewModel.aggiungiLibro(libro146)
                dbViewModel.aggiungiLibro(libro147)
                dbViewModel.aggiungiLibro(libro148)
                dbViewModel.aggiungiLibro(libro149)
                dbViewModel.aggiungiLibro(libro150)

                dbViewModel.aggiungiLibro(libro151)
                dbViewModel.aggiungiLibro(libro152)
                dbViewModel.aggiungiLibro(libro153)
                dbViewModel.aggiungiLibro(libro154)
                dbViewModel.aggiungiLibro(libro155)
                dbViewModel.aggiungiLibro(libro156)
                dbViewModel.aggiungiLibro(libro157)
                dbViewModel.aggiungiLibro(libro158)
                dbViewModel.aggiungiLibro(libro159)
                dbViewModel.aggiungiLibro(libro160)
                dbViewModel.aggiungiLibro(libro161)
                dbViewModel.aggiungiLibro(libro162)
                dbViewModel.aggiungiLibro(libro163)
                dbViewModel.aggiungiLibro(libro164)
                dbViewModel.aggiungiLibro(libro165)
                dbViewModel.aggiungiLibro(libro166)
                dbViewModel.aggiungiLibro(libro167)
                dbViewModel.aggiungiLibro(libro168)
                dbViewModel.aggiungiLibro(libro169)
                dbViewModel.aggiungiLibro(libro170)
                dbViewModel.aggiungiLibro(libro171)
                dbViewModel.aggiungiLibro(libro172)
                dbViewModel.aggiungiLibro(libro173)
                dbViewModel.aggiungiLibro(libro174)
                dbViewModel.aggiungiLibro(libro175)

                dbViewModel.aggiungiLibro(libro176)
                dbViewModel.aggiungiLibro(libro177)
                dbViewModel.aggiungiLibro(libro178)
                dbViewModel.aggiungiLibro(libro179)
                dbViewModel.aggiungiLibro(libro180)
                dbViewModel.aggiungiLibro(libro181)
                dbViewModel.aggiungiLibro(libro182)
                dbViewModel.aggiungiLibro(libro183)
                dbViewModel.aggiungiLibro(libro184)
                dbViewModel.aggiungiLibro(libro185)
                dbViewModel.aggiungiLibro(libro186)
                dbViewModel.aggiungiLibro(libro187)
                dbViewModel.aggiungiLibro(libro188)
                dbViewModel.aggiungiLibro(libro189)
                dbViewModel.aggiungiLibro(libro190)
                dbViewModel.aggiungiLibro(libro191)
                dbViewModel.aggiungiLibro(libro192)
                dbViewModel.aggiungiLibro(libro193)
                dbViewModel.aggiungiLibro(libro194)
                dbViewModel.aggiungiLibro(libro195)
                dbViewModel.aggiungiLibro(libro196)
                dbViewModel.aggiungiLibro(libro197)
                dbViewModel.aggiungiLibro(libro198)
                dbViewModel.aggiungiLibro(libro199)
                dbViewModel.aggiungiLibro(libro200)

                dbViewModel.aggiungiLibro(libro201)
                dbViewModel.aggiungiLibro(libro202)
                dbViewModel.aggiungiLibro(libro203)
                dbViewModel.aggiungiLibro(libro204)
                dbViewModel.aggiungiLibro(libro205)
                dbViewModel.aggiungiLibro(libro206)
                dbViewModel.aggiungiLibro(libro207)
                dbViewModel.aggiungiLibro(libro208)
                dbViewModel.aggiungiLibro(libro209)
                dbViewModel.aggiungiLibro(libro210)
                dbViewModel.aggiungiLibro(libro211)
                dbViewModel.aggiungiLibro(libro212)
                dbViewModel.aggiungiLibro(libro213)
                dbViewModel.aggiungiLibro(libro214)
                dbViewModel.aggiungiLibro(libro215)
                dbViewModel.aggiungiLibro(libro216)
                dbViewModel.aggiungiLibro(libro217)
                dbViewModel.aggiungiLibro(libro218)
                dbViewModel.aggiungiLibro(libro219)
                dbViewModel.aggiungiLibro(libro220)
                dbViewModel.aggiungiLibro(libro221)
                dbViewModel.aggiungiLibro(libro222)
                dbViewModel.aggiungiLibro(libro223)
                dbViewModel.aggiungiLibro(libro224)
                dbViewModel.aggiungiLibro(libro225)

                dbViewModel.aggiungiLibro(libro226)
                dbViewModel.aggiungiLibro(libro227)
                dbViewModel.aggiungiLibro(libro228)
                dbViewModel.aggiungiLibro(libro229)
                dbViewModel.aggiungiLibro(libro230)
                dbViewModel.aggiungiLibro(libro231)
                dbViewModel.aggiungiLibro(libro232)
                dbViewModel.aggiungiLibro(libro233)
                dbViewModel.aggiungiLibro(libro234)
                dbViewModel.aggiungiLibro(libro235)
                dbViewModel.aggiungiLibro(libro236)
                dbViewModel.aggiungiLibro(libro237)
                dbViewModel.aggiungiLibro(libro238)
                dbViewModel.aggiungiLibro(libro239)
                dbViewModel.aggiungiLibro(libro240)
                dbViewModel.aggiungiLibro(libro241)
                dbViewModel.aggiungiLibro(libro242)
                dbViewModel.aggiungiLibro(libro243)
                dbViewModel.aggiungiLibro(libro244)
                dbViewModel.aggiungiLibro(libro245)
                dbViewModel.aggiungiLibro(libro246)
                dbViewModel.aggiungiLibro(libro247)
                dbViewModel.aggiungiLibro(libro248)
                dbViewModel.aggiungiLibro(libro249)
                dbViewModel.aggiungiLibro(libro250)
            }
            withContext(Dispatchers.Main) {
                // Mostra un messaggio di conferma
                Toast.makeText(this@Biblioteca, "Benvenuto nell'Area Biblioteca", Toast.LENGTH_SHORT).show()
            }
        }
    }

}
